# Generated by Django 4.1.7 on 2023-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awc',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
